[app]
name = "lisa-podcast"
version = "1.1.0"

[image]
python_version = "3.10"

[function.fastapi_app]
cpu = 2
memory = 4096
timeout = 300
min_containers = 0
max_containers = 10

[function.audio_podcast_function]
cpu = 2
memory = 4096
timeout = 300
min_containers = 0
max_containers = 5

[function.video_podcast_function]
cpu = 4
memory = 8192
timeout = 600
min_containers = 0
max_containers = 3 